/** Punto único de exportación de los errores del dominio. */
export { ErrorDominio, type CodigoErrorDominio } from "./ErrorDominio";
export { ErrorValidacion } from "./ErrorValidacion";
export { ErrorPacienteNoEncontrado } from "./ErrorPacienteNoEncontrado";
export { ErrorTurnoConflicto } from "./ErrorTurnoConflicto";
export { ErrorTurnoNoEncontrado } from "./ErrorTurnoNoEncontrado";
export { ErrorUsuarioNoEncontrado } from "./ErrorUsuarioNoEncontrado";
export { ErrorAccesoDenegado } from "./ErrorAccesoDenegado";
export { ErrorArchivoInvalido } from "./ErrorArchivoInvalido";
export { ErrorArchivoNoEncontrado } from "./ErrorArchivoNoEncontrado";
export { ErrorAntropometriaNoEncontrada } from "./ErrorAntropometriaNoEncontrada";
export { ErrorAntropometriaDuplicada } from "./ErrorAntropometriaDuplicada";
export { ErrorLaboratorioNoEncontrado } from "./ErrorLaboratorioNoEncontrado";
export { ErrorAlertaAlimentariaNoEncontrada } from "./ErrorAlertaAlimentariaNoEncontrada";
export { ErrorRegistroDiarioNoEncontrado } from "./ErrorRegistroDiarioNoEncontrado";
export { ErrorRecetaNoEncontrada } from "./ErrorRecetaNoEncontrada";
export { ErrorPlanNoEncontrado } from "./ErrorPlanNoEncontrado";
export { ErrorObjetivoNoEncontrado } from "./ErrorObjetivoNoEncontrado";
export { ErrorMaterialNoEncontrado } from "./ErrorMaterialNoEncontrado";
export { ErrorSuplementoNoEncontrado } from "./ErrorSuplementoNoEncontrado";
export { ErrorAlertaSeguimientoNoEncontrada } from "./ErrorAlertaSeguimientoNoEncontrada";
export { ErrorPlantillaNoEncontrada } from "./ErrorPlantillaNoEncontrada";
export { ErrorConversacionNoEncontrada } from "./ErrorConversacionNoEncontrada";
export { ErrorAxiomaNoEncontrado } from "./ErrorAxiomaNoEncontrado";
export { ErrorRecordatorioNoEncontrado } from "./ErrorRecordatorioNoEncontrado";
